### PR TITLE
basemapAT

### PR DESCRIPTION
**Pull request by blackgis**
This is the official opendata background tile server maps from Austria.
Licence is open and correct inserted. Free to use.

### CODE REVIEW

**Comment by simgislab** [comment]
Hi, thanks for these. Will it work for you to add them to http://qms.nextgis.com as well? So that they are immediately available.

**Comment by blackgis** [comment]
Ok, wasn't aware of this website. Is this website connected to the github, or is it standalone?

**Comment by blackgis** [comment]
Just realized that there is no github account login, could you add these?

**Comment by simgislab** [comment]
It is trivial to register and add services and it was meant for people who typically not willing to use git.

A little more info: http://nextgis.com/blog/qms-service/

We'll still merge PRs here, but the plan is to gradually switch to qms.nextgis.com.

**Pull request merged**
