### PR TITLE
added bergfex

### PR DESCRIPTION
**Pull request by kardinal-eros**
topographic maps for Austria

### CODE REVIEW

**Comment by simgislab** [comment]
thanks!

**Comment by kardinal-eros** [comment]
Hi Maxim!

It found out the addition will only be available to users
with in the next build of contributed pack.

"To become available for QuickMapServices plugin,
new release should made by someone with appropriate privileges.“

How long will this take, whom to ask for?

Best wishes,  Roli

**Comment by simgislab** [comment]
couple of days, ping me if I forget!

**Comment by simgislab** [comment]
published

**Comment by kardinal-eros** [comment]
THX

**Pull request merged**
