### PR TITLE
add jersey source

### PR DESCRIPTION
**Pull request by MatzFan**

### CODE REVIEW

**Comment by MatzFan** [comment]
I see you have reverted this data source, was there a problem with it I can fix? Thanks

Bruce

**Comment by simgislab** [comment]
Hi Bruce, sorry for a little mess on my side.

I've merged, but then realized that we don't yet support custom tile CRSes https://github.com/nextgis/quickmapservices/issues/4 so the merged service won't work.

**Comment by MatzFan** [comment]
Understood, no problem. FYI this one is an unusual one: EPSG:3109. [To my knowledge](http://gis.stackexchange.com/questions/162069/wkid-issue-when-adding-raster-layer-from-arcgis-mapserver-to-qgis-via-rest) gdal_translate can't yet deal with this - have just raised issue [#6112](https://trac.osgeo.org/gdal/ticket/6112#ticket) with gdal to see if it can be fixed

**Comment by MatzFan** [comment]
Just noticed that 0.14 release fixes nextgis/quickmapservices#4 - can my layer now be added? Thx

**Comment by yellow-sky** [comment]
Sorry, but not yet. As this service needs custom grid. There is no way yet to set custom grid params for the service definition at the moment.

**Comment by MatzFan** [comment]
OK Evgeniy - many thanks for you work so far anyway, let me know if I can help

**Pull request merged**
