### PR TITLE
Add Here Maps Wego and Mapbox Sources

### PR DESCRIPTION
**Pull request by jo-chemla**
Following this issue: 
https://github.com/nextgis/quickmapservices_contrib/issues/60

### CODE REVIEW

**Comment by jo-chemla** [comment]
Replied on the original issue thread https://github.com/nextgis/quickmapservices_contrib/issues/60
These API keys and tokens were retrieved from the official mapbox and heremaps apps, they are not tied to a specific account, so the PR can be merged.

**Comment by jo-chemla** [comment]
Hi @simgislab, do you plan to merge this PR? Thanks!

Plus could you make qms.nextgis.org accept TMS endpoints which return webp images like for https://qms.nextgis.com/geoservices/6088/ ? Thanks as well!

**Comment by jo-chemla** [comment]
Thanks for the merge!
Fast to update, I can already see Here WeGo Satellite, Hybrid and Terrain added (with date that of the PR) on NextGIS QMS like [here](https://qms.nextgis.com/geoservices/6090/)
The mapbox source is not listed though. Is it because these are **webp** tiles or because I should wait a bit more for propagation of this TLS endpoint? 
Thanks again for your great toolbelt.

**Comment by simgislab** [comment]
qms.nextgis.com sources are completely separate from contrib package, did you add Mapbox there too?

mapbox looks good on contrib package

**Comment by jo-chemla** [comment]
Yes I did also add it there, but it wont be made public because of a validation error on qms.nextgis.com:

`Service is failing validation and can't be made public. Edit it to fix errors or let us know.`

The invalid response error comes with text `service response is not image`, which might occur because mapbox tiles are `webp` images and this case is not yet handled by qms.

**Comment by jo-chemla** [comment]
Hi there, wondering if you had time to simply allow webp tiles in NextGIS QMS - I still cannot publish the Mapbox Service which cannot be validated, although it is shown on the leaflet viewer, simply because tiles are webp.

**Comment by simgislab** [comment]
apologies for making you wait.
 
We've finally come up with some resources for this work and active development will restart soon.
 
We'll keep you posted on this task.

**Comment by jo-chemla** [comment]
No worries, glad this can be worked on! Will follow this thread then. 

PS related to [this thread](https://x.com/jo_chemla/status/1778442268082315513): are you - NextGIS - at some point willing to build a contributive STAC catalog of catalogs, based on the `web map links` extension, the same way you built an open inventory of TMS/WMS etc sources? This could be a nice community driven repo of STAC for non-technical, non-github users.

**Comment by jo-chemla** [comment]
By the way, if there is anything I can do to help push webp tiles TMS, let me know! At the moment, the mapbox satellite source still fails validation https://qms.nextgis.com/geoservices/6088/

**Comment by jo-chemla** [comment]
By the way, if there is anything I can do to help push webp tiles TMS, let me know! At the moment, the mapbox satellite source still fails validation https://qms.nextgis.com/geoservices/6088/

**Comment by jo-chemla** [comment]
By the way, if there is anything I can do to help push webp tiles TMS, let me know! At the moment, the mapbox satellite source still fails validation https://qms.nextgis.com/geoservices/6088/

**Comment by simgislab** [comment]
Hello Jonathan,

I know it's been a long time, but now the work started for real. I'll get back here soon.

Unfortunately quick update didn't work for us, so there will be a major QMS rework.

**Comment by jo-chemla** [comment]
Thank you so much for getting back, don't hesitate if I can be of any help!

**Comment by simgislab** [comment]
Hello, long wait, I know, sorry :)

.webp can now be added to the catalog
https://x.com/nextgis/status/2016522585748423021

**Comment by jo-chemla** [comment]
Thanks for reporting back, no worries for the time it took!
Just edited and published mapbox webp TMS from an `access_token` I had lying around
https://qms.nextgis.com/geoservices/6088/

**Comment by jo-chemla** [comment]
I also tried adding webp TMS tiles for Mapterhorn, which are terrarium encoded zoom 0-16. 
https://qms.nextgis.com/geoservices/9235/#

The leaflet viewer shows the tileset, but the validation is failing, `Tile not found` but which tile request is failing is not exposed. 

I also added webp TMS tiles for: 
 - LINZ [here 9236](https://qms.nextgis.com/geoservices/9236/) although there was a pre-existing jpg tms [here 1359](https://qms.nextgis.com/geoservices/1259/)
 - MapTiler Terrain Hillshade [here 9237](https://qms.nextgis.com/geoservices/9237/)
 - and this linz, and maptiler hillshade, like mapbox, are succeeding validation, not mapterhorn

**Comment by simgislab** [comment]
Looks great!

Lets create a separate issue for mapterhorn problem. 

Thanks

**Pull request merged**
