### PR TITLE
add MapBox Sattelite

### PR DESCRIPTION
**Pull request by spatialhast**

### CODE REVIEW

**Comment by simgislab** [comment]
also note the link is slightly different here: https://github.com/nextgis/quickmapservices_contrib/commit/3a24fb25093c3eaf9c7cfa9340c6b5ddaaf0f5fc

**Comment by spatialhast** [comment]
URL (with public token) I get from JOSM, there MapBox Sattelite is default imagery layer. Possible not to violate the license we should use URL https://api.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.png?access_token=nnn, where nnn - public access_token from own Mapbox user account

**Comment by simgislab** [comment]
ok, should a.tiles be api.tiles? @yellow-sky

**Comment by lyzidiamond** [comment]
Hi, Lyzi from Mapbox here. Some answers to your questions and some thoughts:
- So long as the map isn't cached and each user/device is making a request for tiles, this does not violate our terms of service.
- You can hard-code your own access token or ask users to include their access tokens -- either way you do it is fine.
- The link should point to `api.mapbox.com/v4/ ...` as @simgislab points out above
- Please change the name to "Mapbox Satellite", with a lowercase "b" in Mapbox and Satellite spelled correctly
- Please add documentation to reflect the end-user restrictions with Mapbox Satellite, most importantly attribution and printing:
  - https://www.mapbox.com/help/trace-mapbox-satellite-in-open-street-map/
  - https://www.mapbox.com/help/attribution/
  - https://www.mapbox.com/help/print-satellite/
  - https://www.mapbox.com/help/offline-satellite/

I hope this is helpful! Let me know if you have any other questions.

**Comment by simgislab** [comment]
thanks for info @lyzidiamond

@spatialhast can you make changes to link/attribution/copyrights etc as discussed?

**Comment by spatialhast** [comment]
I fixed URL (add from my own access token)/spelling and attributions https://github.com/spatialhast/quickmapservices_contrib/commit/8bbe9618147dd92a6595ceca07287e0df0f4c5a1. Please check. Thanks!

**Comment by simgislab** [comment]
merged, thanks

release will have to wait though until we fix https://github.com/nextgis/quickmapservices/issues/42

**Pull request merged**
